### ISSUE TITLE
Java and Oclint linters are not installed

### ISSUE THREAD

**Issue by amrondonp** [JuezUN/Deployment#1]
The ruby API for linting code relies on a pre-installed software called coala which at the same time **relies on already installed linters** In the case of pylint, coala installs it with the instalation script. However, Oclint and the java linters are not present in the dockerfile as long as I can see.

LinterService -calls-> Coala -calls-> Oclint

So we must ensure that
1. Oclint and Java Linters are installed
2. The have an environment variable named after the command that is used by coala to call

In the case of Java, it will handled here
https://github.com/JuezUN/coala-bears/blob/master/bears/java/JavaPMDBear.py#L31

In the case of Oclint, Here
https://github.com/JuezUN/coala-bears/blob/master/bears/c_languages/OclintBear.py#L9

In those files you can find the name of the excecutables so that you can include them in the container

**Comment by larranaga** [comment]
they have already been added
