### ISSUE TITLE
Document consideration with server ownership on /var/www/INGInious folder

### ISSUE THREAD

**Issue by amrondonp** [JuezUN/Deployment#35]
If the ownership on the folder /var/www/INGInious is not set correctly, then the application cannot save tasks data or course modifications. The deployment scirpt already does that job for you but when you copy for examples tasks from git to the folder, it would have other ownership than the required. We can document the issue or even better. Have the error shown in the app to be something related with folder ownership so that the admin will know what to to

**Comment by crdgonzalezca** [comment]
With the new uncode_tasks_backup when you restore the tasks (pull from remote repository) it already runs the command to change the owner of all tasks. However, I think I will add some documentation on 'Common Problems' section.

**Comment by crdgonzalezca** [comment]
Documentation added on README.md on 'Common Problems'.
